=== Kubernetes

// Buggy behavior of GitHub
[source, mermaid]
//[mermaid]
....
---
config:
    flowchart:
        defaultRenderer: elk
---
flowchart
    subgraph ext[External Zones]
        subgraph agent-ext[Agents]
            agent-ext-1[Agent]
            agent-ext-2[...]
            agent-ext-3[Agent]
        end
    end
    subgraph im[Intermediate Zones]
        subgraph agent-im[Agents]
            agent-im-1[Agent]
            agent-im-2[...]
            agent-im-3[Agent]
        end
        subgraph proxy-im[Proxies]
            subgraph proxy-im-ny[US]
                proxy-im-usa-1([Envoy])
                proxy-im-usa-2([Envoy])
            end
            subgraph proxy-im-any[...]
                proxy-im-any-1([Envoy])
                proxy-im-any-2([Envoy])
            end
            subgraph proxy-im-eu[EU]
                proxy-im-eu-1([Envoy])
                proxy-im-eu-2([Envoy])
            end
        end
    end
    subgraph int[Internal Zone]
        subgraph agent-int[Agents]
            agent-int-1[Agent]
            agent-int-2[...]
            agent-int-3[Agent]
        end
        subgraph proxy-int[Proxies]
            subgraph proxy-int-int[API Gateway]
                proxy-int-int-1([Envoy])
                proxy-int-int-2([Envoy])
                proxy-int-int-3([Envoy])
                proxy-int-int-4([Envoy])
            end
        end
        subgraph k8s-collector[Kubernetes]
            subgraph k8s-collector-1[Alfa]
                proxy-k8s-1([HTTPProxy])
                collector-1[[Collector]]
                proxy-k8s-1 -- h2c::8080 --> collector-1
            end
            subgraph k8s-collector-2[Bravo]
                proxy-k8s-2([HTTPProxy])
                collector-2[[Collector]]
                proxy-k8s-2 -- h2c::8080 --> collector-2
            end
        end
        subgraph k8s-loader[Kubernetes]
            subgraph k8s-loader-1[Alfa]
                loader-1[[Loader]]
                dbmon-1{{DB Monitor}}
            end
            subgraph k8s-loader-2[Bravo]
                loader-2[[Loader]]
            end
        end
        kafka[(Kafka)]
        db[(Database)]
        collector-1 & collector-2 --> kafka --> loader-1 & loader-2 --> db --> dbmon-1 --> db
    end
    agent-ext -- tcp::7777 --> proxy-im -- h2:api.example.com --> proxy-int
    agent-im & agent-int -- tcp::7777 --> proxy-int
    proxy-int -- h2 --> k8s-collector
....

=== VM/BM

// Buggy behavior of GitHub
[source, mermaid]
//[mermaid]
....
---
config:
    flowchart:
        defaultRenderer: elk
---
flowchart
    subgraph int[Internal Zone]
        subgraph proxy[API Gateway]
            subgraph proxy-eu[EUR]
                proxy-1(["`1
                    Envoy`"])
                proxy-3(["`3
                    Envoy`"])
            end
            subgraph proxy-us[USA]
                proxy-2(["`2
                    Envoy`"])
                proxy-4(["`4
                    Envoy`"])
            end
            proxy-eu ~~~ proxy-us
        end
        subgraph app-1[Heavy App]
            subgraph app-1-eu[EUR]
                app-1-1["`1
                    Envoy
                    Heavy App`"]
                app-1-3["`3
                    Envoy
                    Heavy App`"]
                app-1-5["`5
                    Envoy
                    Heavy App`"]
            end
            subgraph app-1-us[USA]
                app-1-2["`2
                    Envoy
                    Heavy App`"]
                app-1-4["`4
                    Envoy
                    Heavy App`"]
                app-1-6["`6
                    Envoy
                    Heavy App`"]
            end
            app-1-eu ~~~ app-1-us
        end
        subgraph app-2[Light App]
            subgraph app-2-eu[EUR]
                app-2-1["`1
                    Envoy
                    Light App 1
                    Light App 2`"]
                app-2-3["`3
                    Envoy
                    Light App 1
                    Light App 2`"]
            end
            subgraph app-2-us[USA]
                app-2-2["`2
                    Envoy
                    Light App 1
                    Light App 2`"]
                app-2-4["`4
                    Envoy
                    Light App 1
                    Light App 2`"]
            end
            app-2-eu ~~~ app-2-us
        end
    end
    proxy -- h2 --> app-1 & app-2
....
